I create the delete category function in redux action and reducer so i uploaded also a new library called sweetalert2 for delete button so when i click the delete button it takes the id of clicked item and dispatch the the function i fall in a problem that page after this become blank because of  Uncaught TypeError: categories.map is not a function because of that i made a new structure begin with Or || [] in useSelector categories and i make a condition in mapping if categories > 0 or not if it not display that there is no categories founded. I also delete that useEffect and useState of edit button and i navigate directly to that new path